force-app/main/default/objects/Contact/fields/Bench_Status_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Bench_Status_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bench_Status_Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Expected_Bench_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Bench_Date__c</fullName>
    <label>Expected_Bench_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Skills__c.field-meta.xml
<CustomField>
    <fullName>Primary_Skills__c</fullName>
    <label>Primary_Skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job_Application</label>
    <nameField>
        <label>Job_Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Candidate</relationshipLabel>
    <relationshipName>Candidate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Posting</relationshipLabel>
    <relationshipName>Job_Posting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job_Posting</label>
    <nameField>
        <label>Job_Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Required_Grade__c.field-meta.xml
<CustomField>
    <fullName>Required_Grade__c</fullName>
    <label>Required_Grade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>B3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Required_Skills__c.field-meta.xml
<CustomField>
    <fullName>Required_Skills__c</fullName>
    <label>Required_Skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/dummyDatatorun.cls
public class dummyDatatorun {


    public static void batchFired(){
        // Running the batch manually with a scope size of 50
Database.executeBatch(new BenchNotificationBatch(), 50);
System.debug('Batch Job Fired!');
    }

    public static void justToTest(){
// Contact 1: Exactly 30 days left (Initial Email Trigger)
Contact c1 = new Contact(
    LastName = 'Kumar_30DaysTest',
    Email = 'auralwc2021@gmail.com', // Apna actual email id yahan daal
    Expected_Bench_Date__c = Date.today().addDays(30),
    Bench_Status_Confirmed__c = false
);

// Contact 2: Less than 30 days left (Reminder Email Trigger - Will fire because today is Friday)
Contact c2 = new Contact(
    LastName = 'Sharma_ReminderTest',
    Email = 'theprojectj27@gmail.com', // Apna actual email id yahan daal
    Expected_Bench_Date__c = Date.today().addDays(15), 
    Bench_Status_Confirmed__c = false
);

insert new List<Contact>{c1, c2};
System.debug('Dummy Contacts Inserted Successfully!');

    }

public static void schedulefire(){
// Cron Expression for Daily at Midnight
String cronExp = '0 0 0 * * ?';
System.schedule('Daily Bench Notification Check', cronExp, new BenchNotificationBatch());

}
    public static void getDummyData(){

Job_Posting__c job = new Job_Posting__c(
    Name = 'Integration Specialist',
    Required_Grade__c = 'B2',
    Required_Skills__c = 'Apex, LWC, OmniStudio, REST API'
);
insert job;


Contact cand = new Contact(
    LastName = 'Kumar',
    Email = 'test@dummy.com',
    Grade__c = 'B1',
    Primary_Skills__c = 'Apex, LWC, REST API' // OmniStudio is missing
);
insert cand;


Job_Application__c app = new Job_Application__c(
    Candidate__c = cand.Id,
    Job_Posting__c = job.Id
);
insert app;

}
}